export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    try {
        const { message = '', image = null, lang = 'bn' } = req.body || {};

        if (!message && !image) {
            return res.status(400).json({ error: 'Message or image is required' });
        }

        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            return res.status(500).json({ error: 'API key not configured in Vercel.' });
        }

        const language = lang === 'en'
            ? 'Answer in clear English.'
            : 'Answer strictly in simple Bengali for Bangladeshi farmers.';

        const parts = [{
            text: `You are Foshol AI, an expert agriculture assistant for Bangladesh farmers. ${language}
Provide practical and safe farming advice.
User: ${message || 'Analyze this crop image.'}`
        }];

        if (image?.data) {
            parts.push({
                inline_data: {
                    mime_type: image.mimeType || 'image/jpeg',
                    data: image.data.replace(/^data:image\/[a-z]+;base64,/, '')
                }
            });
        }

        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ contents: [{ parts }] })
            }
        );

        const data = await response.json();

        if (!response.ok) {
            console.error('Gemini Error:', data);
            return res.status(500).json({
                error: data.error?.message || 'Gemini API failed'
            });
        }

        const reply = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!reply) {
            return res.status(500).json({ error: 'No response generated by AI' });
        }

        const cleanReply = reply
            .replace(/\*\*(.*?)\*\*/g, '<b>$1</b>')
            .replace(/\n/g, '<br>');

        return res.status(200).json({ reply: cleanReply });

    } catch (error) {
        console.error('Chat API Error:', error);
        return res.status(500).json({
            error: 'Server error. Please try again.'
        });
    }
}
